export const SET_MOVIES = 'SET_MOVIES';
export const SET_SELECTED = 'SET_SELECTED';
export const INCREMENT_LIKES = 'INCREMENT_LIKES';
export const DECREMENT_LIKES = 'DECREMENT_LIKES';
export const SET_RATING = 'SET_RATING';
export const SORT_BY_RATING = 'SORT_BY_RATING';
export const SORT_BY_LIKES = 'SORT_BY_LIKES';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';